sudo: required
services:
  - docker

before_install:
  - docker build -t dre4success/docker-ci -f Dockerfile.dev .

script:
  - docker run dre4success/docker-ci npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-ci"
  env: "DockerCi-env"
  bucket_name: "elasticbeanstalk-eu-west-1-428687659842"
  bucket_path: "docker-ci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
